version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "cobaban"
    ports:
      - "3300:3300"
